### ISSUE TITLE
HttpBackend missing multiple methods in remote mode: conflict, stats.procedural_stats, etc. (v0.5.0)

### ISSUE THREAD

**Issue by acidport** [yantrikos/yantrikdb-mcp#2]
## Summary

When running `yantrikdb-mcp` v0.5.0 in **remote cluster mode** (via `YANTRIKDB_SERVER_URL` pointing at a `yantrikdb serve` backend), several MCP tools fail with `AttributeError` because `HttpBackend` is missing methods that exist in the embedded backend.

Basic CRUD (`remember`, `recall`, `memory`, `forget`, `health`) works correctly. The issue affects the higher-level cognitive tools.

## Environment

| | |
|---|---|
| MCP client | `yantrikdb-mcp 0.5.0` (PyPI) |
| Server image | `ghcr.io/yantrikos/yantrikdb:latest` (digest `9115e3963166`, pulled 2026-04-19) |
| Server OS/arch | Debian Trixie, `linux/arm64` (Oracle Cloud `VM.Standard.A1.Flex`) |
| Server cmd | `yantrikdb serve --data-dir /var/lib/yantrikdb` |
| Clients tested | macOS 14 Tahoe + Windows 11 (Claude Desktop) |
| Transport | HTTP with `YANTRIKDB_SERVER_URL` + `YANTRIKDB_TOKEN`, fronted by Caddy/TLS |

## Steps to reproduce

1. Set up `yantrikdb serve` on a remote host
2. Configure a client with:
```json
   {
     "mcpServers": {
       "yantrikdb": {
         "command": "yantrikdb-mcp",
         "env": {
           "YANTRIKDB_SERVER_URL": "https://<host>",
           "YANTRIKDB_TOKEN": "<token>"
         }
       }
     }
   }
```
3. Call any of the failing tools below

### 1. `conflict` — list

```python
conflict(action="list", status="open", limit=20)
```

**Error:**
```
'_Conflict' object is not subscriptable
```

### 2. `conflict` — get

```python
conflict(action="get", conflict_id="019dbe0c-d245-7689-8c43-34ec28089b16")
```

**Error:**
```
'HttpBackend' object has no attribute 'get_conflict'
```

### 3. `stats` — detailed

```python
stats(action="stats")
```

**Error:**
```
'HttpBackend' object has no attribute 'procedural_stats'
```

`stats(action="health")` works fine.

## Expected

`HttpBackend` should mirror the embedded backend's public surface, or failing that, return a clear "not supported over HTTP transport" message instead of a raw `AttributeError`.

## Suspected scope

Likely missing from `HttpBackend` (not exhaustive — suggesting a systematic audit against the embedded backend):

- `get_conflict`, `list_conflicts`, `resolve_conflict`, `reclassify_conflict`
- `procedural_stats`, `graph_stats`, `weights_stats`
- Possibly methods backing `graph.*`, `trigger.*`, `procedure.*`, `personality.*` tools (not tested exhaustively)

The `_Conflict is not subscriptable` in case 1 suggests a separate issue in how the tool handler deserializes the HTTP response — treating a dataclass as a dict.

## Workaround

For conflict triage I had to stop the container, edit the SQLite DB directly (`sudo sqlite3 /var/lib/yantrikdb/default/yantrik.db`), then restart. Works but defeats the point of having the MCP layer.

## Impact

Users running `yantrikdb-mcp` against a self-hosted `yantrikdb serve` cluster (the shared-server setup documented in the README) cannot use roughly half of the declared tools. Embedded-mode users are unaffected.

Happy to test a patch or gather more debug info.

**Comment by spranab** [comment]
Confirmed — `HttpBackend` in v0.5.0 is missing parity with the embedded backend for the cognitive tools (`conflict`, parts of `stats`, others). Basic CRUD works because those were ported; the higher-level tools were added later and the HTTP wrappers weren't kept in sync.

Fix targeted for **v0.5.1 tonight** (UTC):
- Audit `HttpBackend` against the embedded backend's public surface
- Add HTTP wrappers for every missing method
- Add a CI check that fails the build if `HttpBackend` is missing a method exposed by the embedded backend, so this regression class can't recur

Your repro setup (Oracle Cloud ARM + Caddy/TLS) is great — we'll add it as a smoke target for the remote-mode test matrix.

Will tag you on the commit.

**Comment by spranab** [comment]
Fixed in `yantrikos/yantrikdb-mcp` v0.5.1 (PR #3, just merged + tagged).

**Shipped:**
1. `get_conflicts()` now returns plain dicts — `'_Conflict' object is not subscriptable` is gone (your case 1).
2. New `get_conflict(conflict_id)` — `AttributeError: ... has no attribute 'get_conflict'` is gone (your case 2).
3. New `procedural_stats()` (and 22 other previously-AttributeError methods) raise `RemoteUnsupportedError` (subclass of `NotImplementedError`) with a clear message instead of opaque `AttributeError` (your case 3 + your suspected scope list).
4. Bonus: `resolve_conflict()` was hitting `/v1/conflicts/resolve` (which 404s); fixed to `/v1/conflicts/{id}/resolve`.

`HttpBackend` now exposes 50 methods covering all 40 `db.*` calls in `tools.py`. Methods backed by existing `/v1` endpoints have real implementations; the rest raise the clear `RemoteUnsupportedError` so tool handlers and your tracebacks both get something legible.

**Verified end-to-end** against a running yantrikdb server (PR description has the test transcript).

**Install:**
```sh
pip install -U yantrikdb-mcp==0.5.1
```

**Followups not in this release (worth filing if you want them):**
- Real HTTP endpoints for `procedural_stats`, `archive`, `hydrate`, `entity_profile`, `search_entities`, etc. — the embedded backend has them; right now they raise `RemoteUnsupportedError` over HTTP.
- `reclassify_conflict` HTTP endpoint (`POST /v1/conflicts/{id}/reclassify`).

Thanks for the detailed report (the env block + 3 reproductions + suspected scope list + the workaround note all made this trivially scopeable). The `_Conflict` subscriptable observation in particular pointed straight at the wrap-vs-dict mismatch.

Closing.

**Comment by acidport** [comment]
## Follow-up to #2 — `stats` tool has multiple failures in remote mode (v0.5.1)

**Environment**

| | |
|---|---|
| `yantrikdb-mcp` | 0.5.1 |
| `yantrikdb` (engine) | 0.4.2 |
| Server image | `ghcr.io/yantrikos/yantrikdb:latest` (digest `sha256:ecbe59e1f4bf4eb2189f81b96854f786e5ebb3f0c7f4f3819e106d172be4b150`, pulled 2026-04-28) |
| Python | 3.13.x (Windows, pythoncore-3.13-64) |
| Transport | HTTP remote mode (`YANTRIKDB_SERVER_URL`) |

## What happened

After upgrading to v0.5.1, `conflict(action="list")` works correctly — that fix is confirmed good.

However, all three `stats` actions fail in remote mode, each for a different reason:

| Action | Error |
|---|---|
| `stats(action="stats")` | `HttpBackend.procedural_stats() got an unexpected keyword argument 'namespace'` |
| `stats(action="health")` | `_Stats object has no attribute 'get'` |
| `stats(action="weights")` | `RemoteUnsupportedError` |

## Bug 1 — `stats(action="stats")`: unexpected `namespace` kwarg

The tool schema injects `namespace` as a default kwarg even when not explicitly provided by the user. The MCP retried without the param and still failed, suggesting it is injected unconditionally by the tool layer.

```
HttpBackend.procedural_stats() got an unexpected keyword argument 'namespace'
```

## Bug 2 — `stats(action="health")`: deserialization error

This action does have an HTTP endpoint and `GET /v1/stats` returns a valid response (confirmed via curl). The failure is a client-side deserialization bug — the response object is being treated as a dict when it is not.

```
_Stats object has no attribute 'get'
```

This is distinct from the `namespace` issue and affects an action that should work in remote mode.

## Bug 3 — `stats(action="weights")`: no HTTP endpoint

Raises `RemoteUnsupportedError` as expected per v0.5.1 design. Not a regression, but worth noting for the followup endpoint roadmap mentioned in the release notes.

## Steps to reproduce

1. Configure `yantrikdb-mcp` 0.5.1 in remote mode against a `yantrikdb serve` backend
2. Call `stats(action="stats")` — observe `namespace` kwarg error
3. Call `stats(action="health")` — observe `_Stats object has no attribute 'get'`
4. Call `stats(action="weights")` — observe `RemoteUnsupportedError`

## Expected

- `stats(action="stats")`: raise `RemoteUnsupportedError` cleanly (no kwarg injection)
- `stats(action="health")`: return health data — the HTTP endpoint exists and works
- `stats(action="weights")`: current behavior acceptable, but could include a hint

## Notes

- Bug 2 (`health`) is the highest priority — the endpoint works server-side, the failure is purely client-side deserialization
- Confirmed on both macOS and Windows clients
- Bug persists on latest server image pulled 2026-04-28 — confirmed as MCP client issue

**Comment by spranab** [comment]
Three for three confirmed and shipped in v0.5.2 — thanks for the fast turnaround on testing v0.5.1.

Honest take: this was the same bug class as the `_Conflict` issue from your original report, just on a different class. v0.5.1 fixed `_Conflict` but I missed `_Stats`. That's a real miss on my end — your `'_Conflict' object is not subscriptable` observation should have prompted a sweep across every wrapper class, not just the one that triggered the report.

## Fixed in v0.5.2

- **`stats(action="stats")`** — `_Stats` now subclasses `dict`, so `result["procedural"] = ...` (the subscript-set in `tools.py`) works. `procedural_stats(*args, **kw)` accepts the `namespace` kwarg the tool layer injects (and any other defensive kwargs it might pass).
- **`stats(action="health")`** — same `_Stats(dict)` change exposes `.get`, `.keys`, iteration. Legacy `s.active_memories` attribute access still works via `__getattr__`.
- **`stats(action="weights")`** — still raises `RemoteUnsupportedError` (no `/v1` endpoint exists for adapted recall weights yet), but the message now points at embedded-mode workaround explicitly.

All 23 unsupported-method stubs now accept `*args, **kw` defensively, so future tool-layer kwarg injection won't TypeError before the clean `RemoteUnsupportedError` fires.

## Install

```sh
pip install -U yantrikdb-mcp==0.5.2
```

## E2E verified

```
[OK] stats(action='stats')   subscript-set on _Stats           keys: ['active_memories', ...]
[OK] stats(action='health')  .get() on _Stats                  active=2 entities=3 conflicts=0
[OK] stats(action='weights') raises with hint                  RemoteUnsupportedError + embedded-mode pointer
[OK] legacy attribute access still works                       s.active_memories=2
[OK] procedural_stats(namespace=...) accepts kwargs            no TypeError
```

## Structural fix to prevent v0.5.3 having the same problem

The pattern bit me twice — fixing one wrapper at a time means the next wrapper class with the same problem ships broken. Adding to the v0.6.0 plan:

- **CI contract test** that fails the build if `HttpBackend` is missing any method `tools.py` calls, or returns a class that doesn't expose the same access patterns (`__getitem__`, `.get`, attribute access) as the embedded backend's return values for the same call.
- That's exactly the kind of regression you flagged in your original "Suspected scope" list — *"return a clear 'not supported over HTTP transport' message instead of a raw `AttributeError`"*. Generalizing to **"surface contract parity"** captures it.

If the contract test sounds useful for your remote-mode setup, happy to scope a small `tests/test_backend_parity.py` that pins the `tools.py` call surface and runs in CI on every PR. Saves us both the round-trip next time.

Thanks again — the structured environment block, three concrete reproductions per action, and the explicit "Bug 2 is highest priority" triage made this trivially scopeable. The v0.5.2 commit cites you again.

**Comment by spranab** [comment]
Followed through on the contract test from yesterday's reply — and it caught **11 more gaps in v0.5.2** that I'd otherwise have shipped silently.

Shipped in v0.5.3:

## The contract test ([`tests/test_backend_parity.py`](https://github.com/yantrikos/yantrikdb-mcp/blob/main/tests/test_backend_parity.py))

Fully static — no server, no network, runs in <1s on every PR. Three checks:

1. **Method coverage** — walks `tools.py` AST for every `db.X(...)` call, asserts `HttpBackend` exposes each one. (Catches the v0.5.0 `'HttpBackend has no attribute get_conflict'` class.)
2. **Wrapper-class dict-compat** — every adapter class supports both subscript (`r["key"]`) and attribute (`r.key`) access. (Catches the v0.5.1 `'_Stats has no attribute get'` class.)
3. **Stub kwarg defensiveness** — every `RemoteUnsupportedError` stub accepts `**kw`. (Catches the v0.5.1 `'procedural_stats() got an unexpected keyword argument namespace'` class.)

## What the test caught when first run against v0.5.2

- **7 missing methods** that `tools.py` calls but v0.5.2 didn't define: `session_start` (now real impl: `POST /v1/sessions`), `set_personality_trait`, `stale`, `substitution_categories`, `substitution_members`, `surface_procedural`, `upcoming` (stubs)
- **`reclassify_conflict`** had a typed positional signature; converted to `*args, **kw` like the others
- **4 wrapper classes** (`_Conflict`, `_ThinkResult`, `_Edge`, `_ResolveResult`) were attribute-only; converted to dict subclasses via a shared `_DictWrapper` base. Legacy `r.field` access still works via `__getattr__`. `_ThinkResult` also normalises the server's `consolidations` field to `consolidation_count` so both names work.

So the v0.5.1 → v0.5.2 → v0.5.3 sequence has fixed:
- 1 missing method (v0.5.1: `get_conflict`)
- 8 missing methods total (v0.5.3: + the 7 above)
- 5 wrapper classes now dict-compat (`_Stats` in v0.5.2 + 4 more in v0.5.3)
- 24 stubs now kwarg-defensive (23 in v0.5.2 + `reclassify_conflict` in v0.5.3)

## Install

```sh
pip install -U yantrikdb-mcp==0.5.3
```

## What this means going forward

The contract test runs on every PR via the existing `ci.yml`. Any future tool added to `tools.py` that needs a new `db.X()` call will fail CI until `HttpBackend` has a corresponding method. Any new wrapper class will fail until it's dict-compat. Any new stub that takes typed positional kwargs will fail until it accepts `**kw`. The pattern that bit us four times in three releases now can't ship to PyPI without being caught.

Thanks again — your structured environment block + three concrete reproductions per action + the explicit "Suspected scope" hint list weren't just useful for the original fix, they directly motivated the contract test design. The "surface contract parity" framing in your suspected-scope is now codified in CI.
